### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Sammidysam** [EnvironmentalDashboard/show-and-tell#1]
I was just wondering what our basis of naming this `show-and-tell` is?  Is this repository to be used for more than just the Tensorflow algorithm implementation?

**Comment by Terf** [comment]
The repo we're trying to run is called [Show and Tell: A Neural Image Caption Generator](https://github.com/tensorflow/models/tree/master/research/im2txt#show-and-tell-a-neural-image-caption-generator). This repo is just for the Dockerfile to run said repo but I imagine we'll keep the generated model here as well once we run it.

**Comment by Sammidysam** [comment]
Sounds good - closing and providing this link / description in the readme.
